DROP TABLE URL_MAPPING CASCADE CONSTRAINTS;

DROP SEQUENCE URL_MAPPING_SEQ;

CREATE SEQUENCE URL_MAPPING_SEQ
START WITH 0
INCREMENT BY 1
MAXVALUE 9999999999999999999
MINVALUE 0
NOCACHE
NOCYCLE
NOORDER;

CREATE TABLE URL_MAPPING (
	NO NUMBER DEFAULT 1 NOT NULL,
	ORIGIN_URL VARCHAR2(4000) NOT NULL,
	SHORT_URL VARCHAR2(100),
	SHORTEN_DATE DATE NOT NULL
);

CREATE UNIQUE INDEX PK_URL_MAPPING
   ON URL_MAPPING (
      ORIGIN_URL ASC
   );
   
ALTER TABLE URL_MAPPING
   ADD
      CONSTRAINT PK_URL_MAPPING
      PRIMARY KEY (
         ORIGIN_URL
      );      